name: Super-Linter

on: push

permissions:
  contents: read

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8ef6be64070da8c5ef30fc7decd7f58197779958 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@4ce2083652cb932a76f2eb5fb22067759a2da38d # v8.7.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
